### ISSUE TITLE
How to change label color with CoNLL-U format?

### ISSUE THREAD

**Issue by laurent-brisson** [spyysalo/annodoc#15]
Hello !

First, thanks for this great tool :)

I wonder how to change label color in CoNLL-U format visualization. I found the file config.js where I can specify bgColor and borderColor, but I want to select these colors using the value in the MISC field of CoNLL-U format and not the CPOSTAG field.

Anyone could help me please ?

**Comment by spyysalo** [comment]
Thanks @laurent-brisson, glad it's useful to you!

Support for fine-grained custom styling is provided using "structured comments", see http://spyysalo.github.io/conllu.js/. As an example, you can say

```
# visual-style 1    bgColor:blue
# visual-style 2 1 nsubj    color:blue
```

to make the background of the first token and the color of the `nsubj` relation from the 2nd to the 1st token blue. Hope this helps!

**Comment by laurent-brisson** [comment]
Yes it helps ! Thank you for your quick answer !
