### ISSUE TITLE
annotation flag not visualized correctly

### ISSUE THREAD

**Issue by spyysalo** [spyysalo/annodoc#3]
also, configuration instructions not clear

**Comment by TomokoOhta** [comment]
for NII-English-relations-manual, only `NAME` flag is visualized correctly, why??
that's why I've been confused and looking for some "default" setting for this.

**Comment by spyysalo** [comment]
@TomokoOhta : Only `Name` is configured there, but this is the wrong repo for comments on that.

**Comment by spyysalo** [comment]
Wasn't this fixed already in the relevant repo? Can I close this?

**Comment by TomokoOhta** [comment]
please go ahead
