### ISSUE TITLE
generate PDF

### ISSUE THREAD

**Issue by TomokoOhta** [spyysalo/annodoc#5]
as discussed, we'll generate PDF file as soon as it's ready
burn CD-ROM including the PDF and html source files in ~~serve~~ `_site` after running `jekyll build`

**Comment by spyysalo** [comment]
>  files in `serve`

`_site`, perhaps? :-)

**Comment by TomokoOhta** [comment]
ah, right!
thanks for correction :-)

**Comment by spyysalo** [comment]
can this be closed?

**Comment by TomokoOhta** [comment]
Yes, please ;-)

**Comment by spyysalo** [comment]
Thanks, done!
